### ISSUE TITLE
[beta] new version is not starting

### ISSUE THREAD

**Issue by BiggA94** [crowdrender/cr-docker#4]
Hi,
I just wanted to give the neww beta version a try, but there is a problem.
I think in https://github.com/crowdrender/cr-docker/blob/d3a2edb6e0ce9eedadcb9a443f8af5b43071b52a/start_cr_server.sh#L34
needs to be distinguished between blender versions.

Logs in order to see the error:
```
installing crowdrender addon.......

Blender 2.91.0 (hash 0f45cab862b8 built 2020-11-25 08:51:08)

found bundled python: /usr/local/blender/2.91/python

Info: Modules Installed (crowdrender) from '/CR/cr_029_bl280.zip' into '/root/.config/blender/2.91/scripts/addons'

Writing userprefs: '/root/.config/blender/2.91/config/userpref.blend' ok

addon_utils.disable: crowdrender not disabled

Modules Installed (crowdrender) from '/CR/cr_029_bl280.zip' into '/root/.config/blender/2.91/scripts/addons'

Info: Modules Installed (crowdrender) from '/CR/cr_029_bl280.zip' into '/root/.config/blender/2.91/scripts/addons'

dodgy, but trying to unregister anyway

blender launch test:

Blender 2.91.0 (hash 0f45cab862b8 built 2020-11-25 08:51:08)

Blender 2.91.0

	build date: 2020-11-25

	build time: 08:51:08

	build commit date: 2020-11-25

	build commit time: 08:34

	build hash: 0f45cab862b8

	build platform: Linux

	build type: Release

	build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5  -fuse-ld=gold -std=gnu11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2 -D_GLIBCXX_USE_CXX11_ABI=0

	build c++ flags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5  -fuse-ld=gold -std=c++17   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2 -D_GLIBCXX_USE_CXX11_ABI=0

	build link flags:  -Wl,--version-script='/home/sources/buildbot-worker-linux_centos7/linux_291/blender.git/source/creator/blender.map'

	build system: CMake

starting crowdrender server.....................

Blender 2.91.0 (hash 0f45cab862b8 built 2020-11-25 08:51:08)

Read prefs: /root/.config/blender/2.91/config/userpref.blend

found bundled python: /usr/local/blender/2.91/python

Crowd Render Server Interface Process ready

dodgy, but trying to unregister anyway

Crowd Render add-on Disabled

OSError: Python file "/root/.config/blender/2.83/scripts/addons/crowdrender/src/py_3_7/serv_int_start.py" could not be opened: No such file or directory

Blender quit
```

**Comment by Jeducious** [comment]
Yeah, this looks like the files were installed into 2.91 where they should have been installed into 2.83

**Comment by Jeducious** [comment]
Actually just re-read this, looks like you were actually trying to run 2.91? And after reading [cr-docker/start_cr_server.sh](https://github.com/crowdrender/cr-docker/blob/d3a2edb6e0ce9eedadcb9a443f8af5b43071b52a/start_cr_server.sh#L34), yeah, seems we've hard coded 2.83 to run instead of using the version of blender actually requested to run.

**Comment by BiggA94** [comment]
Yes, trying to run 2.9.1 (hence the beta tag).

**Comment by zocker-160** [comment]
bug confirmed thank you for reporting

**Comment by zocker-160** [comment]
should be fixed now, please can you confirm it working now @BiggA94 ?

**Comment by BiggA94** [comment]
At least Partially fixed.
The docker container does not exit now.
But the server does not show up in my local Blender, while it does with the "latest" tag.
But I think, this is another bug.

**Comment by Jeducious** [comment]
Hi @BiggA94 are you able to confirm,

1. your client/master is logged in properly to your cloud account? You should see your cloud credit balance show up, even if it's zero. 
2. Your auth token you provide to the container is correct?

Also, if you can view your terminal output from your container, and check for any other errors?

**Comment by Jeducious** [comment]
Closed issue since the problem as described in the original post has been fixed.
